In [396]:
import pandas as pd
from pathlib import Path
import plotly.express as px
import numpy as np

In [397]:
# LOADING THE DATAFRAME

data_file = Path('..') / 'data' / 'train.csv'
df = pd.read_csv(data_file, sep=',')

In [398]:
# DATA SET PREVIEW

pd.set_option("display.max_columns", None)
df.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [399]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [400]:
# CONVERT OBJECT TO STRING

columns_object = df.select_dtypes(include='object')
columns_str = columns_object.convert_dtypes(convert_string=True)

df[columns_object.columns] = columns_str

In [401]:
# STRING NORMALIZATION

df.columns = df.columns.str.upper()
columns_str = df.select_dtypes(include='string')

for col in columns_str.columns:
    df[col] = df[col].str.upper()

In [402]:
null_values = df.isnull().mean()*100
null_values[null_values > 0].sort_values(ascending=False).round(2)

POOLQC          99.52
MISCFEATURE     96.30
ALLEY           93.77
FENCE           80.75
MASVNRTYPE      59.73
FIREPLACEQU     47.26
LOTFRONTAGE     17.74
GARAGETYPE       5.55
GARAGEYRBLT      5.55
GARAGEFINISH     5.55
GARAGEQUAL       5.55
GARAGECOND       5.55
BSMTEXPOSURE     2.60
BSMTFINTYPE2     2.60
BSMTQUAL         2.53
BSMTCOND         2.53
BSMTFINTYPE1     2.53
MASVNRAREA       0.55
ELECTRICAL       0.07
dtype: float64

In [403]:
high_missing_cols = null_values[null_values > 40]
medium_missing_cols = null_values[(null_values < 40) & (null_values > 10)]
low_missing_cols = null_values[null_values < 10]

df = df.drop(high_missing_cols.index, axis=1)
df = df.dropna(subset=low_missing_cols.index)
df[medium_missing_cols.index] = df[medium_missing_cols.index].fillna(df[medium_missing_cols.index].mean())

In [404]:
columns_qual_nom = [
    'MSSUBCLASS', 'MSZONING', 'STREET', 'LANDCONTOUR', 'UTILITIES',
    'LOTCONFIG', 'LANDSLOPE', 'NEIGHBORHOOD', 'CONDITION1', 'CONDITION2',
    'BLDGTYPE', 'HOUSESTYLE', 'ROOFSTYLE', 'ROOFMATL', 'EXTERIOR1ST',
    'EXTERIOR2ND', 'FOUNDATION', 'HEATING', 'CENTRALAIR', 'ELECTRICAL',
    'GARAGETYPE', 'GARAGEFINISH', 'PAVEDDRIVE', 'SALETYPE', 'SALECONDITION'
]

columns_qual_ord = [
    'LOTSHAPE', 'OVERALLQUAL', 'OVERALLCOND', 'EXTERQUAL', 'EXTERCOND',
    'BSMTQUAL', 'BSMTCOND', 'BSMTEXPOSURE', 'BSMTFINTYPE1', 'BSMTFINTYPE2',
    'HEATINGQC', 'KITCHENQUAL', 'FUNCTIONAL', 'GARAGEQUAL', 'GARAGECOND'
]

columns_quan_disc = [
    'YEARBUILT', 'YEARREMODADD', 'BSMTFULLBATH', 'BSMTHALFBATH', 'FULLBATH',
    'HALFBATH', 'BEDROOMABVGR', 'KITCHENABVGR', 'TOTRMSABVGRD', 'FIREPLACES',
    'GARAGEYRBLT', 'GARAGECARS', 'MOSOLD', 'YRSOLD'
]

columns_quan_cont = [
    'LOTFRONTAGE', 'LOTAREA', 'MASVNRAREA', 'BSMTFINSF1', 'BSMTFINSF2',
    'BSMTUNFSF', 'TOTALBSMTSF', '1STFLRSF', '2NDFLRSF', 'LOWQUALFINSF',
    'GRLIVAREA', 'GARAGEAREA', 'WOODDECKSF', 'OPENPORCHSF', 'ENCLOSEDPORCH',
    '3SSNPORCH', 'SCREENPORCH', 'POOLAREA', 'MISCVAL', 'SALEPRICE'
]

In [405]:
df.head()

,ID,MSSUBCLASS,MSZONING,LOTFRONTAGE,LOTAREA,STREET,LOTSHAPE,LANDCONTOUR,UTILITIES,LOTCONFIG,LANDSLOPE,NEIGHBORHOOD,CONDITION1,CONDITION2,BLDGTYPE,HOUSESTYLE,OVERALLQUAL,OVERALLCOND,YEARBUILT,YEARREMODADD,ROOFSTYLE,ROOFMATL,EXTERIOR1ST,EXTERIOR2ND,MASVNRAREA,EXTERQUAL,EXTERCOND,FOUNDATION,BSMTQUAL,BSMTCOND,BSMTEXPOSURE,BSMTFINTYPE1,BSMTFINSF1,BSMTFINTYPE2,BSMTFINSF2,BSMTUNFSF,TOTALBSMTSF,HEATING,HEATINGQC,CENTRALAIR,ELECTRICAL,1STFLRSF,2NDFLRSF,LOWQUALFINSF,GRLIVAREA,BSMTFULLBATH,BSMTHALFBATH,FULLBATH,HALFBATH,BEDROOMABVGR,KITCHENABVGR,KITCHENQUAL,TOTRMSABVGRD,FUNCTIONAL,FIREPLACES,GARAGETYPE,GARAGEYRBLT,GARAGEFINISH,GARAGECARS,GARAGEAREA,GARAGEQUAL,GARAGECOND,PAVEDDRIVE,WOODDECKSF,OPENPORCHSF,ENCLOSEDPORCH,3SSNPORCH,SCREENPORCH,POOLAREA,MISCVAL,MOSOLD,YRSOLD,SALETYPE,SALECONDITION,SALEPRICE
0,1,60,RL,65.0,8450,PAVE,REG,LVL,ALLPUB,INSIDE,GTL,COLLGCR,NORM,NORM,1FAM,2STORY,7,5,2003,2003,GABLE,COMPSHG,VINYLSD,VINYLSD,196.0,GD,TA,PCONC,GD,TA,NO,GLQ,706,UNF,0,150,856,GASA,EX,Y,SBRKR,856,854,0,1710,1,0,2,1,3,1,GD,8,TYP,0,ATTCHD,2003.0,RFN,2,548,TA,TA,Y,0,61,0,0,0,0,0,2,2008,WD,NORMAL,208500
1,2,20,RL,80.0,9600,PAVE,REG,LVL,ALLPUB,FR2,GTL,VEENKER,FEEDR,NORM,1FAM,1STORY,6,8,1976,1976,GABLE,COMPSHG,METALSD,METALSD,0.0,TA,TA,CBLOCK,GD,TA,GD,ALQ,978,UNF,0,284,1262,GASA,EX,Y,SBRKR,1262,0,0,1262,0,1,2,0,3,1,TA,6,TYP,1,ATTCHD,1976.0,RFN,2,460,TA,TA,Y,298,0,0,0,0,0,0,5,2007,WD,NORMAL,181500
2,3,60,RL,68.0,11250,PAVE,IR1,LVL,ALLPUB,INSIDE,GTL,COLLGCR,NORM,NORM,1FAM,2STORY,7,5,2001,2002,GABLE,COMPSHG,VINYLSD,VINYLSD,162.0,GD,TA,PCONC,GD,TA,MN,GLQ,486,UNF,0,434,920,GASA,EX,Y,SBRKR,920,866,0,1786,1,0,2,1,3,1,GD,6,TYP,1,ATTCHD,2001.0,RFN,2,608,TA,TA,Y,0,42,0,0,0,0,0,9,2008,WD,NORMAL,223500
3,4,70,RL,60.0,9550,PAVE,IR1,LVL,ALLPUB,CORNER,GTL,CRAWFOR,NORM,NORM,1FAM,2STORY,7,5,1915,1970,GABLE,COMPSHG,WD SDNG,WD SHNG,0.0,TA,TA,BRKTIL,TA,GD,NO,ALQ,216,UNF,0,540,756,GASA,GD,Y,SBRKR,961,756,0,1717,1,0,1,0,3,1,GD,7,TYP,1,DETCHD,1998.0,UNF,3,642,TA,TA,Y,0,35,272,0,0,0,0,2,2006,WD,ABNORML,140000
4,5,60,RL,84.0,14260,PAVE,IR1,LVL,ALLPUB,FR2,GTL,NORIDGE,NORM,NORM,1FAM,2STORY,8,5,2000,2000,GABLE,COMPSHG,VINYLSD,VINYLSD,350.0,GD,TA,PCONC,GD,TA,AV,GLQ,655,UNF,0,490,1145,GASA,EX,Y,SBRKR,1145,1053,0,2198,1,0,2,1,4,1,GD,9,TYP,1,ATTCHD,2000.0,RFN,3,836,TA,TA,Y,192,84,0,0,0,0,0,12,2008,WD,NORMAL,250000

# Exploring

In [406]:
skewness = {}

for col in columns_quan_cont:
    skewness[col] = df[col].skew()

df_skewness = pd.DataFrame.from_dict(skewness, orient="index")

columns_to_log = df_skewness[(df_skewness > 1) & ((df_skewness < -1))]
columns_normal = df_skewness[(df_skewness < 1) & ((df_skewness > -1))].dropna()

In [407]:
df_outlier_log = df[columns_to_log.index].copy()

for col in df_outlier_log:
    df_outlier_log[col] = np.log1p(df_outlier_log[col])