# Data Cleaning

In [703]:
from pathlib import Path
import pandas as pd
import numpy as np

In [704]:
# PATH DEFINITIONS
BASE_DIR = Path().resolve().parent

DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "data_raw"

CLEAN_DATA_DIR = DATA_DIR / "data_clean"
CLEAN_DATA_DIR.mkdir(exist_ok=True)

In [705]:
df_raw = df_raw = pd.read_csv(RAW_DATA_DIR / "train.csv")

## String treatment

In [706]:
df_str_treat = df_raw.copy()

In [707]:
df_str_treat.columns = df_str_treat.columns.str.upper()
columns_str = df_str_treat.select_dtypes(include='string')

for col in columns_str.columns:
    df_str_treat[col] = df_str_treat[col].str.upper()

pd.set_option('display.max_columns', None)
df_str_treat.head()

,ID,MSSUBCLASS,MSZONING,LOTFRONTAGE,LOTAREA,STREET,ALLEY,LOTSHAPE,LANDCONTOUR,UTILITIES,LOTCONFIG,LANDSLOPE,NEIGHBORHOOD,CONDITION1,CONDITION2,BLDGTYPE,HOUSESTYLE,OVERALLQUAL,OVERALLCOND,YEARBUILT,YEARREMODADD,ROOFSTYLE,ROOFMATL,EXTERIOR1ST,EXTERIOR2ND,MASVNRTYPE,MASVNRAREA,EXTERQUAL,EXTERCOND,FOUNDATION,BSMTQUAL,BSMTCOND,BSMTEXPOSURE,BSMTFINTYPE1,BSMTFINSF1,BSMTFINTYPE2,BSMTFINSF2,BSMTUNFSF,TOTALBSMTSF,HEATING,HEATINGQC,CENTRALAIR,ELECTRICAL,1STFLRSF,2NDFLRSF,LOWQUALFINSF,GRLIVAREA,BSMTFULLBATH,BSMTHALFBATH,FULLBATH,HALFBATH,BEDROOMABVGR,KITCHENABVGR,KITCHENQUAL,TOTRMSABVGRD,FUNCTIONAL,FIREPLACES,FIREPLACEQU,GARAGETYPE,GARAGEYRBLT,GARAGEFINISH,GARAGECARS,GARAGEAREA,GARAGEQUAL,GARAGECOND,PAVEDDRIVE,WOODDECKSF,OPENPORCHSF,ENCLOSEDPORCH,3SSNPORCH,SCREENPORCH,POOLAREA,POOLQC,FENCE,MISCFEATURE,MISCVAL,MOSOLD,YRSOLD,SALETYPE,SALECONDITION,SALEPRICE
0,1,60,RL,65.0,8450,PAVE,NaN,REG,LVL,ALLPUB,INSIDE,GTL,COLLGCR,NORM,NORM,1FAM,2STORY,7,5,2003,2003,GABLE,COMPSHG,VINYLSD,VINYLSD,BRKFACE,196.0,GD,TA,PCONC,GD,TA,NO,GLQ,706,UNF,0,150,856,GASA,EX,Y,SBRKR,856,854,0,1710,1,0,2,1,3,1,GD,8,TYP,0,NaN,ATTCHD,2003.0,RFN,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,NORMAL,208500
1,2,20,RL,80.0,9600,PAVE,NaN,REG,LVL,ALLPUB,FR2,GTL,VEENKER,FEEDR,NORM,1FAM,1STORY,6,8,1976,1976,GABLE,COMPSHG,METALSD,METALSD,NaN,0.0,TA,TA,CBLOCK,GD,TA,GD,ALQ,978,UNF,0,284,1262,GASA,EX,Y,SBRKR,1262,0,0,1262,0,1,2,0,3,1,TA,6,TYP,1,TA,ATTCHD,1976.0,RFN,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,NORMAL,181500
2,3,60,RL,68.0,11250,PAVE,NaN,IR1,LVL,ALLPUB,INSIDE,GTL,COLLGCR,NORM,NORM,1FAM,2STORY,7,5,2001,2002,GABLE,COMPSHG,VINYLSD,VINYLSD,BRKFACE,162.0,GD,TA,PCONC,GD,TA,MN,GLQ,486,UNF,0,434,920,GASA,EX,Y,SBRKR,920,866,0,1786,1,0,2,1,3,1,GD,6,TYP,1,TA,ATTCHD,2001.0,RFN,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,NORMAL,223500
3,4,70,RL,60.0,9550,PAVE,NaN,IR1,LVL,ALLPUB,CORNER,GTL,CRAWFOR,NORM,NORM,1FAM,2STORY,7,5,1915,1970,GABLE,COMPSHG,WD SDNG,WD SHNG,NaN,0.0,TA,TA,BRKTIL,TA,GD,NO,ALQ,216,UNF,0,540,756,GASA,GD,Y,SBRKR,961,756,0,1717,1,0,1,0,3,1,GD,7,TYP,1,GD,DETCHD,1998.0,UNF,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,ABNORML,140000
4,5,60,RL,84.0,14260,PAVE,NaN,IR1,LVL,ALLPUB,FR2,GTL,NORIDGE,NORM,NORM,1FAM,2STORY,8,5,2000,2000,GABLE,COMPSHG,VINYLSD,VINYLSD,BRKFACE,350.0,GD,TA,PCONC,GD,TA,AV,GLQ,655,UNF,0,490,1145,GASA,EX,Y,SBRKR,1145,1053,0,2198,1,0,2,1,4,1,GD,9,TYP,1,TA,ATTCHD,2000.0,RFN,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,NORMAL,250000

## Null treatment

In [708]:
df_null_treat = df_str_treat.copy()

In [709]:
# GARAGE ANALYSIS

garage_columns = ['GARAGEQUAL', 'GARAGEFINISH', 'GARAGETYPE', 'GARAGEYRBLT','GARAGECOND']

df_null_treat_garage = df_null_treat[garage_columns].copy()
df_null_treat_garage = df_null_treat_garage[df_null_treat_garage['GARAGEYRBLT'].isnull()].reset_index(drop='True')
df_null_treat_garage.isnull().sum()

GARAGEQUAL      81
GARAGEFINISH    81
GARAGETYPE      81
GARAGEYRBLT     81
GARAGECOND      81
dtype: int64

In [710]:
# GARAGEYRBLT 
df_null_treat['HASGARAGE'] = np.where(df_null_treat['GARAGEYRBLT'].isnull(), 0, 1).astype('int8')
df_null_treat = df_null_treat.drop(columns='GARAGEYRBLT')

garage_columns = ['GARAGEQUAL', 'GARAGEFINISH', 'GARAGETYPE', 'GARAGECOND', 'HASGARAGE']

# OTHERS
df_null_treat['GARAGEQUAL'] = df_null_treat['GARAGETYPE'].fillna('NA')
df_null_treat['GARAGEFINISH'] = df_null_treat['GARAGETYPE'].fillna('NA')
df_null_treat['GARAGETYPE'] = df_null_treat['GARAGETYPE'].fillna('NA')
df_null_treat['GARAGECOND'] = df_null_treat['GARAGETYPE'].fillna('NA')

df_null_treat[garage_columns].isnull().sum()

GARAGEQUAL      0
GARAGEFINISH    0
GARAGETYPE      0
GARAGECOND      0
HASGARAGE       0
dtype: int64

In [711]:
bsmt_columns = ['BSMTFINTYPE2', 'BSMTEXPOSURE', 'BSMTCOND', 'BSMTQUAL', 'BSMTFINTYPE1']

df_null_treat_bsmt = df_null_treat[bsmt_columns].copy()
df_null_treat_bsmt.isnull().sum()

BSMTFINTYPE2    38
BSMTEXPOSURE    38
BSMTCOND        37
BSMTQUAL        37
BSMTFINTYPE1    37
dtype: int64

In [712]:
# OTHERS
df_null_treat['BSMTCOND'] = df_null_treat['BSMTCOND'].fillna('NA')
df_null_treat['BSMTQUAL'] = df_null_treat['BSMTQUAL'].fillna('NA')
df_null_treat['BSMTFINTYPE1'] = df_null_treat['BSMTFINTYPE1'].fillna('NA')

mask = (df_null_treat_bsmt['BSMTCOND'].notnull()) & ((df_null_treat_bsmt['BSMTEXPOSURE'].isnull()) | (df_null_treat_bsmt['BSMTFINTYPE2'].isnull()))
filter = ~mask
df_null_treat = df_null_treat[filter].reset_index(drop=True)

df_null_treat['BSMTFINTYPE2'] = df_null_treat['BSMTCOND'].fillna('NA')
df_null_treat['BSMTEXPOSURE'] = df_null_treat['BSMTQUAL'].fillna('NA')

df_null_treat[bsmt_columns].isnull().sum()

BSMTFINTYPE2    0
BSMTEXPOSURE    0
BSMTCOND        0
BSMTQUAL        0
BSMTFINTYPE1    0
dtype: int64

In [713]:
# NULLS PER COLUMN AND PERCENTAGE OF NULLS PER COLUMN

nulls_per_column = df_null_treat.isnull().sum()
percentage_nulls_per_column = df_null_treat.isnull().mean()
nulls_per_column = pd.DataFrame(nulls_per_column)
nulls_per_column = nulls_per_column.rename(columns={0: 'SUM'})
nulls_per_column['%'] = percentage_nulls_per_column.round(4)*100
nulls_per_column = nulls_per_column.sort_values(by='SUM', ascending=False)

nulls_per_column[nulls_per_column['SUM'] > 0]

              SUM      %
POOLQC       1451  99.52
MISCFEATURE  1404  96.30
ALLEY        1367  93.76
FENCE        1177  80.73
MASVNRTYPE    872  59.81
FIREPLACEQU   690  47.33
LOTFRONTAGE   259  17.76
MASVNRAREA      8   0.55
ELECTRICAL      1   0.07

In [714]:
df_null_treat = df_null_treat.dropna(subset=['ELECTRICAL', 'MASVNRAREA'])

In [715]:
# POOL ANALYSIS

df_null_treat_pool = df_null_treat[['POOLQC', 'POOLAREA']].copy()
pool_mask = (df_null_treat_pool['POOLQC'].notnull())
df_null_treat_pool = df_null_treat_pool[pool_mask]

df_null_treat_pool

     POOLQC  POOLAREA
197      EX       512
809      FA       648
1168     GD       576
1180     EX       555
1296     GD       480
1384     FA       519
1421     GD       738

In [716]:
# POOL TREATMENT

df_null_treat['HASPOOL'] = np.where(df_null_treat['POOLQC'].isnull(), 0, 1).astype('int8')
df_null_treat = df_null_treat.drop(columns=['POOLQC', 'POOLAREA'])

In [717]:
# FIREPLACE ANALYSIS

df_null_treat_fireplace = df_null_treat[['FIREPLACES', 'FIREPLACEQU']].copy()
fireplace_mask = (df_null_treat_fireplace['FIREPLACEQU'].isnull() & df_null_treat_fireplace['FIREPLACES'] > 0)
df_null_treat_fireplace = df_null_treat_fireplace[fireplace_mask]

df_null_treat_fireplace

Empty DataFrame
Columns: [FIREPLACES, FIREPLACEQU]
Index: []

In [718]:
df_null_treat['FIREPLACEQU'] = df_null_treat['FIREPLACEQU'].fillna('NA')

In [719]:
# GENERAL

df_null_treat['MISCFEATURE'] = df_null_treat['MISCFEATURE'].fillna('NA')
df_null_treat['ALLEY'] = df_null_treat['MISCFEATURE'].fillna('NA')
df_null_treat['FENCE'] = df_null_treat['MISCFEATURE'].fillna('NA')
df_null_treat['MASVNRTYPE'] = df_null_treat['MASVNRTYPE'].fillna('None')
df_null_treat['LOTFRONTAGE'] = df_null_treat['LOTFRONTAGE'].fillna(0)

In [724]:
nulls_per_column = df_null_treat.isnull().sum()
percentage_nulls_per_column = df_null_treat.isnull().mean()

nulls_per_column = pd.DataFrame(nulls_per_column)
nulls_per_column = nulls_per_column.rename(columns={0: 'SUM'})
nulls_per_column['%'] = percentage_nulls_per_column.round(4)*100
nulls_per_column = nulls_per_column.sort_values(by='SUM', ascending=False)

nulls_per_column[nulls_per_column['SUM'] > 0]

Empty DataFrame
Columns: [SUM, %]
Index: []

## Types treatment

In [721]:
df_null_treat_bsmt.isnull().sum()

BSMTFINTYPE2    38
BSMTEXPOSURE    38
BSMTCOND        37
BSMTQUAL        37
BSMTFINTYPE1    37
dtype: int64

In [722]:
df_type_treat = df_null_treat.copy()

df_type_treat.info()

<class 'pandas.DataFrame'>
Index: 1449 entries, 0 to 1457
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             1449 non-null   int64
 1   MSSUBCLASS     1449 non-null   int64
 2   MSZONING       1449 non-null   str
 3   LOTFRONTAGE    1449 non-null   float64
 4   LOTAREA        1449 non-null   int64
 5   STREET         1449 non-null   str
 6   ALLEY          1449 non-null   str
 7   LOTSHAPE       1449 non-null   str
 8   LANDCONTOUR    1449 non-null   str
 9   UTILITIES      1449 non-null   str
 10  LOTCONFIG      1449 non-null   str
 11  LANDSLOPE      1449 non-null   str
 12  NEIGHBORHOOD   1449 non-null   str
 13  CONDITION1     1449 non-null   str
 14  CONDITION2     1449 non-null   str
 15  BLDGTYPE       1449 non-null   str
 16  HOUSESTYLE     1449 non-null   str
 17  OVERALLQUAL    1449 non-null   int64
 18  OVERALLCOND    1449 non-null   int64
 19  YEARBUILT      1449 non-null   int64
 20  YEARREMODADD   1449 non-null   int64
 21  ROOFSTYLE      1449 non-null   str
 22  ROOFMATL       1449 non-null   str
 23  EXTERIOR1ST    1449 non-null   str
 24  EXTERIOR2ND    1449 non-null   str
 25  MASVNRTYPE     1449 non-null   str
 26  MASVNRAREA     1449 non-null   float64
 27  EXTERQUAL      1449 non-null   str
 28  EXTERCOND      1449 non-null   str
 29  FOUNDATION     1449 non-null   str
 30  BSMTQUAL       1449 non-null   str
 31  BSMTCOND       1449 non-null   str
 32  BSMTEXPOSURE   1449 non-null   str
 33  BSMTFINTYPE1   1449 non-null   str
 34  BSMTFINSF1     1449 non-null   int64
 35  BSMTFINTYPE2   1449 non-null   str
 36  BSMTFINSF2     1449 non-null   int64
 37  BSMTUNFSF      1449 non-null   int64
 38  TOTALBSMTSF    1449 non-null   int64
 39  HEATING        1449 non-null   str
 40  HEATINGQC      1449 non-null   str
 41  CENTRALAIR     1449 non-null   str
 42  ELECTRICAL     1449 non-null   str
 43  1STFLRSF       1449 non-null   int64
 44  2NDFLRSF       1449 non-null   int64
 45  LOWQUALFINSF   1449 non-null   int64
 46  GRLIVAREA      1449 non-null   int64
 47  BSMTFULLBATH   1449 non-null   int64
 48  BSMTHALFBATH   1449 non-null   int64
 49  FULLBATH       1449 non-null   int64
 50  HALFBATH       1449 non-null   int64
 51  BEDROOMABVGR   1449 non-null   int64
 52  KITCHENABVGR   1449 non-null   int64
 53  KITCHENQUAL    1449 non-null   str
 54  TOTRMSABVGRD   1449 non-null   int64
 55  FUNCTIONAL     1449 non-null   str
 56  FIREPLACES     1449 non-null   int64
 57  FIREPLACEQU    1449 non-null   str
 58  GARAGETYPE     1449 non-null   str
 59  GARAGEFINISH   1449 non-null   str
 60  GARAGECARS     1449 non-null   int64
 61  GARAGEAREA     1449 non-null   int64
 62  GARAGEQUAL     1449 non-null   str
 63  GARAGECOND     1449 non-null   str
 64  PAVEDDRIVE     1449 non-null   str
 65  WOODDECKSF     1449 non-null   int64
 66  OPENPORCHSF    1449 non-null   int64
 67  ENCLOSEDPORCH  1449 non-null   int64
 68  3SSNPORCH      1449 non-null   int64
 69  SCREENPORCH    1449 non-null   int64
 70  FENCE          1449 non-null   str
 71  MISCFEATURE    1449 non-null   str
 72  MISCVAL        1449 non-null   int64
 73  MOSOLD         1449 non-null   int64
 74  YRSOLD         1449 non-null   int64
 75  SALETYPE       1449 non-null   str
 76  SALECONDITION  1449 non-null   str
 77  SALEPRICE      1449 non-null   int64
 78  HASGARAGE      1449 non-null   int8
 79  HASPOOL        1449 non-null   int8
dtypes: float64(2), int64(34), int8(2), str(42)
memory usage: 897.1 KB

In [723]:
measure_varibles = [
    "LOTAREA",
    "BSMTFINSF1",
    "BSMTFINSF2",
    "BSMTUNFSF",
    "TOTALBSMTSF",
    "1STFLRSF",
    "2NDFLRSF",
    "LOWQUALFINSF",
    "GRLIVAREA",
    "GARAGEAREA",
    "WOODDECKSF",
    "OPENPORCHSF",
    "ENCLOSEDPORCH",
    "3SSNPORCH",
    "SCREENPORCH",
    "POOLAREA",
]

df_type_treat[measure_varibles] = df_type_treat[measure_varibles].astype('float64')
df_type_treat['GARAGEYRBLT'] = df_type_treat['GARAGEYRBLT'].astype('int64')

KeyError: "['POOLAREA'] not in index"